// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: horus/wireguard/v1/agent.proto

// Control ↔ agente del hub WireGuard (rol wg-agent, contenedor con CAP_NET_ADMIN; docs/api.md §5.3).
// ApplyDesiredState es idempotente (estado completo + versión); el agente es fail-static.

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DesiredPeer peer que debe existir en el hub (sin claves privadas: la del router nunca sale del router).
type DesiredPeer struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PeerId                     string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	TenantId                   string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	PublicKey                  string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AllowedIps                 []string               `protobuf:"bytes,4,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	PersistentKeepaliveSeconds int32                  `protobuf:"varint,5,opt,name=persistent_keepalive_seconds,json=persistentKeepaliveSeconds,proto3" json:"persistent_keepalive_seconds,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *DesiredPeer) Reset() {
	*x = DesiredPeer{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredPeer) ProtoMessage() {}

func (x *DesiredPeer) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredPeer.ProtoReflect.Descriptor instead.
func (*DesiredPeer) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *DesiredPeer) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *DesiredPeer) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DesiredPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DesiredPeer) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *DesiredPeer) GetPersistentKeepaliveSeconds() int32 {
	if x != nil {
		return x.PersistentKeepaliveSeconds
	}
	return 0
}

// ApplyDesiredStateRequest estado completo del hub.
type ApplyDesiredStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HubId          string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	DesiredVersion int64                  `protobuf:"varint,2,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	Peers          []*DesiredPeer         `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyDesiredStateRequest) Reset() {
	*x = ApplyDesiredStateRequest{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDesiredStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDesiredStateRequest) ProtoMessage() {}

func (x *ApplyDesiredStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDesiredStateRequest.ProtoReflect.Descriptor instead.
func (*ApplyDesiredStateRequest) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyDesiredStateRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *ApplyDesiredStateRequest) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *ApplyDesiredStateRequest) GetPeers() []*DesiredPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// ApplyDesiredStateResponse versión aplicada.
type ApplyDesiredStateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppliedVersion int64                  `protobuf:"varint,1,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	PeersAdded     int32                  `protobuf:"varint,2,opt,name=peers_added,json=peersAdded,proto3" json:"peers_added,omitempty"`
	PeersRemoved   int32                  `protobuf:"varint,3,opt,name=peers_removed,json=peersRemoved,proto3" json:"peers_removed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyDesiredStateResponse) Reset() {
	*x = ApplyDesiredStateResponse{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyDesiredStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyDesiredStateResponse) ProtoMessage() {}

func (x *ApplyDesiredStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyDesiredStateResponse.ProtoReflect.Descriptor instead.
func (*ApplyDesiredStateResponse) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ApplyDesiredStateResponse) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *ApplyDesiredStateResponse) GetPeersAdded() int32 {
	if x != nil {
		return x.PeersAdded
	}
	return 0
}

func (x *ApplyDesiredStateResponse) GetPeersRemoved() int32 {
	if x != nil {
		return x.PeersRemoved
	}
	return 0
}

// ObservedPeer estado observado de un peer.
type ObservedPeer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PublicKey       string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Endpoint        *string                `protobuf:"bytes,2,opt,name=endpoint,proto3,oneof" json:"endpoint,omitempty"`
	LastHandshakeAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_handshake_at,json=lastHandshakeAt,proto3,oneof" json:"last_handshake_at,omitempty"`
	RxBytes         uint64                 `protobuf:"varint,4,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes         uint64                 `protobuf:"varint,5,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObservedPeer) Reset() {
	*x = ObservedPeer{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedPeer) ProtoMessage() {}

func (x *ObservedPeer) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedPeer.ProtoReflect.Descriptor instead.
func (*ObservedPeer) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ObservedPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ObservedPeer) GetEndpoint() string {
	if x != nil && x.Endpoint != nil {
		return *x.Endpoint
	}
	return ""
}

func (x *ObservedPeer) GetLastHandshakeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHandshakeAt
	}
	return nil
}

func (x *ObservedPeer) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *ObservedPeer) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

// ReportStatusRequest reporte periódico del agente.
type ReportStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HubId          string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	AppliedVersion int64                  `protobuf:"varint,2,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	ObservedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	InterfaceUp    bool                   `protobuf:"varint,4,opt,name=interface_up,json=interfaceUp,proto3" json:"interface_up,omitempty"`
	Peers          []*ObservedPeer        `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportStatusRequest) Reset() {
	*x = ReportStatusRequest{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusRequest) ProtoMessage() {}

func (x *ReportStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusRequest.ProtoReflect.Descriptor instead.
func (*ReportStatusRequest) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReportStatusRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *ReportStatusRequest) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *ReportStatusRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *ReportStatusRequest) GetInterfaceUp() bool {
	if x != nil {
		return x.InterfaceUp
	}
	return false
}

func (x *ReportStatusRequest) GetPeers() []*ObservedPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

// ReportStatusResponse indica si el agente debe pedir el estado deseado de nuevo.
type ReportStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DesiredVersion int64                  `protobuf:"varint,1,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportStatusResponse) Reset() {
	*x = ReportStatusResponse{}
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportStatusResponse) ProtoMessage() {}

func (x *ReportStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_horus_wireguard_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportStatusResponse.ProtoReflect.Descriptor instead.
func (*ReportStatusResponse) Descriptor() ([]byte, []int) {
	return file_horus_wireguard_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ReportStatusResponse) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

var File_horus_wireguard_v1_agent_proto protoreflect.FileDescriptor

const file_horus_wireguard_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x1ehorus/wireguard/v1/agent.proto\x12\x12horus.wireguard.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc5\x01\n" +
	"\vDesiredPeer\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vallowed_ips\x18\x04 \x03(\tR\n" +
	"allowedIps\x12@\n" +
	"\x1cpersistent_keepalive_seconds\x18\x05 \x01(\x05R\x1apersistentKeepaliveSeconds\"\x91\x01\n" +
	"\x18ApplyDesiredStateRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12'\n" +
	"\x0fdesired_version\x18\x02 \x01(\x03R\x0edesiredVersion\x125\n" +
	"\x05peers\x18\x03 \x03(\v2\x1f.horus.wireguard.v1.DesiredPeerR\x05peers\"\x8a\x01\n" +
	"\x19ApplyDesiredStateResponse\x12'\n" +
	"\x0fapplied_version\x18\x01 \x01(\x03R\x0eappliedVersion\x12\x1f\n" +
	"\vpeers_added\x18\x02 \x01(\x05R\n" +
	"peersAdded\x12#\n" +
	"\rpeers_removed\x18\x03 \x01(\x05R\fpeersRemoved\"\xf4\x01\n" +
	"\fObservedPeer\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\bendpoint\x18\x02 \x01(\tH\x00R\bendpoint\x88\x01\x01\x12K\n" +
	"\x11last_handshake_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x0flastHandshakeAt\x88\x01\x01\x12\x19\n" +
	"\brx_bytes\x18\x04 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x05 \x01(\x04R\atxBytesB\v\n" +
	"\t_endpointB\x14\n" +
	"\x12_last_handshake_at\"\xed\x01\n" +
	"\x13ReportStatusRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12'\n" +
	"\x0fapplied_version\x18\x02 \x01(\x03R\x0eappliedVersion\x12;\n" +
	"\vobserved_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12!\n" +
	"\finterface_up\x18\x04 \x01(\bR\vinterfaceUp\x126\n" +
	"\x05peers\x18\x05 \x03(\v2 .horus.wireguard.v1.ObservedPeerR\x05peers\"?\n" +
	"\x14ReportStatusResponse\x12'\n" +
	"\x0fdesired_version\x18\x01 \x01(\x03R\x0edesiredVersion2\x80\x01\n" +
	"\fAgentService\x12p\n" +
	"\x11ApplyDesiredState\x12,.horus.wireguard.v1.ApplyDesiredStateRequest\x1a-.horus.wireguard.v1.ApplyDesiredStateResponse2s\n" +
	"\x0eControlService\x12a\n" +
	"\fReportStatus\x12'.horus.wireguard.v1.ReportStatusRequest\x1a(.horus.wireguard.v1.ReportStatusResponseb\x06proto3"

var (
	file_horus_wireguard_v1_agent_proto_rawDescOnce sync.Once
	file_horus_wireguard_v1_agent_proto_rawDescData []byte
)

func file_horus_wireguard_v1_agent_proto_rawDescGZIP() []byte {
	file_horus_wireguard_v1_agent_proto_rawDescOnce.Do(func() {
		file_horus_wireguard_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_horus_wireguard_v1_agent_proto_rawDesc), len(file_horus_wireguard_v1_agent_proto_rawDesc)))
	})
	return file_horus_wireguard_v1_agent_proto_rawDescData
}

var file_horus_wireguard_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_horus_wireguard_v1_agent_proto_goTypes = []any{
	(*DesiredPeer)(nil),               // 0: horus.wireguard.v1.DesiredPeer
	(*ApplyDesiredStateRequest)(nil),  // 1: horus.wireguard.v1.ApplyDesiredStateRequest
	(*ApplyDesiredStateResponse)(nil), // 2: horus.wireguard.v1.ApplyDesiredStateResponse
	(*ObservedPeer)(nil),              // 3: horus.wireguard.v1.ObservedPeer
	(*ReportStatusRequest)(nil),       // 4: horus.wireguard.v1.ReportStatusRequest
	(*ReportStatusResponse)(nil),      // 5: horus.wireguard.v1.ReportStatusResponse
	(*timestamppb.Timestamp)(nil),     // 6: google.protobuf.Timestamp
}
var file_horus_wireguard_v1_agent_proto_depIdxs = []int32{
	0, // 0: horus.wireguard.v1.ApplyDesiredStateRequest.peers:type_name -> horus.wireguard.v1.DesiredPeer
	6, // 1: horus.wireguard.v1.ObservedPeer.last_handshake_at:type_name -> google.protobuf.Timestamp
	6, // 2: horus.wireguard.v1.ReportStatusRequest.observed_at:type_name -> google.protobuf.Timestamp
	3, // 3: horus.wireguard.v1.ReportStatusRequest.peers:type_name -> horus.wireguard.v1.ObservedPeer
	1, // 4: horus.wireguard.v1.AgentService.ApplyDesiredState:input_type -> horus.wireguard.v1.ApplyDesiredStateRequest
	4, // 5: horus.wireguard.v1.ControlService.ReportStatus:input_type -> horus.wireguard.v1.ReportStatusRequest
	2, // 6: horus.wireguard.v1.AgentService.ApplyDesiredState:output_type -> horus.wireguard.v1.ApplyDesiredStateResponse
	5, // 7: horus.wireguard.v1.ControlService.ReportStatus:output_type -> horus.wireguard.v1.ReportStatusResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_horus_wireguard_v1_agent_proto_init() }
func file_horus_wireguard_v1_agent_proto_init() {
	if File_horus_wireguard_v1_agent_proto != nil {
		return
	}
	file_horus_wireguard_v1_agent_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_horus_wireguard_v1_agent_proto_rawDesc), len(file_horus_wireguard_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_horus_wireguard_v1_agent_proto_goTypes,
		DependencyIndexes: file_horus_wireguard_v1_agent_proto_depIdxs,
		MessageInfos:      file_horus_wireguard_v1_agent_proto_msgTypes,
	}.Build()
	File_horus_wireguard_v1_agent_proto = out.File
	file_horus_wireguard_v1_agent_proto_goTypes = nil
	file_horus_wireguard_v1_agent_proto_depIdxs = nil
}
